POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

###

GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2
}

###

DELETE http://localhost:3003/api/users/60db36dd79faa2139c5a5b78

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "hellas1234"
}
###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "superuser",
  "password": "root"
}
###

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwZGI3NTJiMjUyZjNmMmZlOGJiNTgxYiIsImlhdCI6MTYyNDk5Njg3MH0.UquDduwOfovgod61bWzXPQnLgvCaYReJYffFmdPOSQs

{
  "title": "Linux basics",
  "author": "Superuser",
  "url": "http://linux.com",
  "likes": 54
}

###

DELETE http://localhost:3003/api/blogs/60db3aab9ded832c8c5057f2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MGRiMzFhZGZmMmViNTI5YWNlMDc3MTAiLCJpYXQiOjE2MjQ5ODc0MTZ9.R8FErzvZsxMbs9yqQsrkgoo1VhF3UGohKmejXfPoRQU